# Generated by Django 4.2.1 on 2023-05-21 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_product_delete_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
