# Generated by Django 4.1.7 on 2023-06-11 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationBillard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_billard', models.CharField(choices=[('blackball', 'blackball'), ('snooker', 'snooker'), ('mini-snooker', 'mini-snooker')], default='blackball', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='reservationtable',
            name='date',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ReservationEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('num_guests', models.PositiveIntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
