# Generated by Django 4.1.7 on 2023-06-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_reservationbillard_alter_reservationtable_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationtable',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
