# Generated by Django 4.1.7 on 2023-06-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservationtable_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationBillard',
        ),
        migrations.AddField(
            model_name='reservationtable',
            name='type',
            field=models.CharField(choices=[('table', 'table'), ('etudiant', 'etudiant'), ('billard', 'billard')], default='table', max_length=200),
        ),
        migrations.DeleteModel(
            name='ReservationEtudiant',
        ),
    ]
