# Generated by Django 4.1.7 on 2023-06-18 12:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_delete_reservationbillard_reservationtable_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservationTable',
            new_name='Reservation',
        ),
    ]
