# Generated by Django 4.1.7 on 2023-06-18 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_rename_reservationtable_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='type',
            new_name='reservation_type',
        ),
    ]
