# Generated by Django 4.2.1 on 2023-06-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayedOrder',
        ),
    ]
