# Generated by Django 4.2.1 on 2023-06-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_delete_payedorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
